name: Portfolio Deployment CI
on:
  push:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: Deploy
        uses: crazy-max/ghaction-github-page@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
